# Generated by Django 5.0.4 on 2024-04-29 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='teacher',
        ),
        migrations.AddField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses_enrolled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='courses_taught', to='myapp.teachers'),
        ),
    ]
